# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d1ea5d70e24b98e3cd21bcfacafb7f7617998e084a1912a8a15fed3125dfc3a83d87e47a1ce9322815ee8bcefd9dcfeeba74f2e3bbf8c5211f4dfbb36e5c266

test:
  secret_key_base: 22654551bc9c20ab8c9f0d30925bb9c8a0a8151d5126120b8c45db95d4399ab55c94c574055389f7e3904d293fc30fb0de16464c0910fffe843f84aacfae8b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
